# Generated by Django 4.1.1 on 2022-09-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='restricted',
            new_name='superuser',
        ),
        migrations.AddField(
            model_name='topic',
            name='restricted_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
