# Generated by Django 4.1.1 on 2022-09-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_restricted_topic_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='superuser',
            new_name='restricted_superuser',
        ),
    ]
