# Generated by Django 4.1.1 on 2022-09-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_superuser_topic_restricted_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='locked',
            new_name='post_locked',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='visible',
            new_name='post_visible',
        ),
        migrations.AddField(
            model_name='post',
            name='post_sticky',
            field=models.BooleanField(default=False),
        ),
    ]
