# Generated by Django 4.1.1 on 2022-09-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_locked_post_post_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_visible',
            field=models.BooleanField(default=True),
        ),
    ]
