# Generated by Django 4.1.1 on 2022-09-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_comment_sticky'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='visible',
        ),
    ]
