# Generated by Django 4.1.1 on 2022-10-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_comment_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(max_length=5000),
        ),
    ]
