# Generated by Django 4.1.1 on 2022-10-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_privacy_policy',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_social_links_facebook',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_social_links_instagram',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_social_links_twitter',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_terms_of_service',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
